services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    entrypoint: ""
    command: /root/docker-entrypoint-dev.sh
